# cmake/LLVMConfig.cmake

# Full list of LLVM components
set(LLVM_COMPONENTS
    all-targets
    analysis
    asmparser
    asmprinter
    bitreader
    bitwriter
    codegen
    core
    coroutines
    debuginfodwarf
    debuginfopdb
    demangle
    executionengine
    frontendopenmp
    instcombine
    instrumentation
    interpreter
    irreader
    ipo
    linker
    lto
    mc
    mcanalysis
    mcdisassembler
    mcjit
    objcarcopts
    object
    option
    passes
    profiledata
    remarks
    scalaropts
    selectiondag
    support
    target
    transformutils
    vectorize
    x86asmparser
    x86codegen
    x86desc
    x86disassembler
    x86info
)